name: build-windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-release:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: npm install && npm run tauri build
      - uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: latest
          prerelease: false
          title: Release ${{ github.sha }}
          files: ./src-tauri/target/release/bundle/**/*
